//
//  BookListViewModel.swift
//  BookStore
//
//  Created by Ambika on 8/7/20.
//  Copyright © 2020 BookStore. All rights reserved.
//

import Foundation



struct BookListViewModel {
    
    private let booklist : [Book]
    var count : Int {
        get {
            return booklist.count
        }
    }
    
    init() {
        let book1 = Book(image: "image1", name: "oliver twist", description: "Oliver Twist is notable for its unromantic portrayal of criminals and their sordid lives, as well as for exposing the cruel treatment of the many orphans in London in the mid-19th century.", publishedDate: "1838", author: "Charles John Huffam Dickens")
        let book2 = Book(image: "image2", name: "The Alchemist", description: "Paulo Coelho's enchanting novel has inspired a devoted following around the world. This story, dazzling in its powerful simplicity and soul-stirring wisdom, is about an Andalusian shepherd boy named Santiago who travels from his homeland in Spain to the Egyptian desert in search of a treasure buried near the Pyramids. ", publishedDate: "1988", author: "Paulo Coelho")
        let book3 = Book(image: "image3", name: "Harry Potter and the Philosopher's Stone", description: "Harry makes close friends and a few enemies during his first year at the school, and with the help of his friends, Harry faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.", publishedDate: "1997", author: "J. K. Rowling")
        let book4 = Book(image: "image4", name: "Harry Potter and the Chamber of Secrets", description: "Harry Potter and the Chamber of Secrets is a fantasy novel written by British author J. K. Rowling and the second novel in the Harry Potter series. The plot follows Harry's second year at Hogwarts School of Witchcraft and Wizardry, during which a series of messages on the walls of the school's corridors warn that the Chamber of Secrets has been opened and that the heir of Slytherin would kill all pupils who do not come from all-magical families. These threats are found after attacks that leave residents of the school petrified. Throughout the year, Harry and his friends Ron and Hermione investigate the attacks.", publishedDate: "1998", author: "J. K. Rowling")
        let book5 = Book(image: "image5", name: "Harry Potter and the Prisoner of Azkaban", description: "Harry Potter and the Prisoner of Azkaban is a fantasy novel written by British author J.K. Rowling and is the third in the Harry Potter series. The book follows Harry Potter, a young wizard, in his third year at Hogwarts School of Witchcraft and Wizardry. Along with friends Ronald Weasley and Hermione Granger, Harry investigates Sirius Black, an escaped prisoner from Azkaban, the wizard prison, believed to be one of Lord Voldemort's old allies.", publishedDate: "1999", author: "J. K. Rowling")
        let book6 = Book(image: "image6", name: "Harry Potter and the Goblet of Fire", description: "Harry Potter and the Goblet of Fire is a fantasy book written by British author J. K. Rowling and the fourth novel in the Harry Potter series. It follows Harry Potter, a wizard in his fourth year at Hogwarts School of Witchcraft and Wizardry, and the mystery surrounding the entry of Harry's name into the Triwizard Tournament, in which he is forced to compete.", publishedDate: "2000", author: "J. K. Rowling")
        let book7 = Book(image: "image7", name: "Harry Potter and the Order of the Phoenix", description: "Harry Potter and the Order of the Phoenix is a fantasy novel written by British author J. K. Rowling and the fifth novel in the Harry Potter series. It follows Harry Potter's struggles through his fifth year at Hogwarts School of Witchcraft and Wizardry, including the surreptitious return of the antagonist Lord Voldemort, O.W.L. exams, and an obstructive Ministry of Magic. The novel was published on 21 June 2003 by Bloomsbury in the United Kingdom, Scholastic in the United States, and Raincoast in Canada. It sold five million copies in the first 24 hours of publication.[1] It is the longest book of the series.", publishedDate: "2003", author: "J. K. Rowling")
        let book8 = Book(image: "image8", name: "Harry Potter and the Half-Blood Prince", description: "Harry Potter and the Half-Blood Prince is a fantasy novel written by British author J.K. Rowling and the sixth and penultimate novel in the Harry Potter series. Set during Harry Potter's sixth year at Hogwarts, the novel explores the past of Harry's nemesis, Lord Voldemort, and Harry's preparations for the final battle against Voldemort alongside his headmaster and mentor Albus Dumbledore.", publishedDate: "2005", author: "J. K. Rowling")
        let book9 = Book(image: "image9", name: "Harry Potter and the Deathly Hallows", description: "Harry Potter and the Deathly Hallows is a fantasy novel written by British author J. K. Rowling and the seventh and final novel of the Harry Potter series. It was released on 21 July 2007 in the United Kingdom by Bloomsbury Publishing, in the United States by Scholastic, and in Canada by Raincoast Books. The novel chronicles the events directly following Harry Potter and the Half-Blood Prince (2005) and the final confrontation between the wizards Harry Potter and Lord Voldemort.", publishedDate: "2007", author: "J. K. Rowling")
        let book10 = Book(image: "image10", name: "Harry Potter and the Deathly Hallows – Part 2", description: "Harry Potter and the Deathly Hallows – Part 2 is a 2011 fantasy film directed by David Yates and distributed by Warner Bros. Pictures.[4] It is the second of two cinematic parts based on J. K. Rowling's 2007 novel of the same name.[5] The film, which is the eighth and final instalment in the Harry Potter film series, was written by Steve Kloves and produced by David Heyman, David Barron, and Rowling. The story continues to follow Harry Potter's quest to find and destroy Lord Voldemort's Horcruxes in order to stop him once and for all.", publishedDate: "2009", author: "J. K. Rowling")
        
        let book11 = Book(image: "image11", name: "Lord of the Rings: The Fellowship of the Ring", description: "The Fellowship of the Ring is the first of three volumes of the epic[2] novel The Lord of the Rings by the English author J. R. R. Tolkien. It is followed by The Two Towers and The Return of the King. It takes place in the fictional universe of Middle-earth. It was originally published on 29 July 1954 in the United Kingdom.", publishedDate: "1954", author: "J. R. R. Tolkien")
        let book12 = Book(image: "image12", name: "Lord of the Rings: The Two Towers", description: "The Two Towers is the second volume of J. R. R. Tolkien's high fantasy novel The Lord of the Rings. It is preceded by The Fellowship of the Ring and followed by The Return of the King.", publishedDate: "1954", author: "J. R. R. Tolkien")
        let book13 = Book(image: "image13", name: "The Lord of the Rings: The Return of the King", description: "The Return of the King is the third and final volume of J. R. R. Tolkien's The Lord of the Rings, following The Fellowship of the Ring and The Two Towers. The story begins in the kingdom of Gondor, which is soon to be attacked by the Dark Lord Sauron.", publishedDate: "1955", author: "J. R. R. Tolkien")
        let book14 = Book(image: "image14", name: "The Hobbit: An Unexpected Journey", description: "The Hobbit: An Unexpected Journey is a 2012 epic high fantasy adventure film directed by Peter Jackson. It is the first installment in a three-part film adaptation based on J. R. R. Tolkien’s 1937 novel The Hobbit. It is followed by The Desolation of Smaug (2013) and The Battle of the Five Armies (2014), and together, they act as a prequel to Jackson's The Lord of the Rings film trilogy. The film's screenplay was written by Jackson, his longtime collaborators Fran Walsh and Philippa Boyens, and Guillermo del Toro, who was originally chosen to direct the film before leaving the project in 2010.", publishedDate: "2012", author: "J. R. R. Tolkien")
        let book15 = Book(image: "image15", name: "The Hobbit: The Desolation of Smaug", description: "The Hobbit: The Desolation of Smaug is a 2013 epic high-fantasy adventure film directed by Peter Jackson and produced by WingNut Films in collaboration with New Line Cinema and Metro-Goldwyn-Mayer. It was distributed by Warner Bros. Pictures and is the second installment in the three-part film series based on the novel The Hobbit by J. R. R. Tolkien. The film was preceded by An Unexpected Journey (2012) and followed by The Battle of the Five Armies (2014); together they operate as a prequel to Jackson's The Lord of the Rings film trilogy.", publishedDate: "2013", author: "J. R. R. Tolkien")
        let book16 = Book(image: "image16", name: "The Hobbit: The Battle of the Five Armies", description: "The Hobbit: The Battle of the Five Armies is a 2014 epic high fantasy film directed by Peter Jackson and written by Jackson, Fran Walsh, Philippa Boyens, and Guillermo del Toro. It is the third and final installment in Peter Jackson's three-part film adaptation based on the novel The Hobbit by J. R. R. Tolkien, following An Unexpected Journey (2012) and The Desolation of Smaug (2013), and together, they act as a prequel to Jackson's The Lord of the Rings film trilogy.", publishedDate: "2014", author: "J. R. R. Tolkien")
        
        let book17 = Book(image: "image17", name: "The Immortals of Meluha", description: "The Immortals of Meluha is the first book of Amish Tripathi, first book of Amishverse, and also the first book of Shiva Trilogy. The story is set in the land of Meluha and starts with the arrival of the Shiva. The Meluhans believe that Shiva is their fabled saviour Neelkanth. Shiva decides to help the Meluhans in their war against the Chandravanshis, who had joined forces with a cursed Nagas; however, during his journey and the fight that ensues, Shiva learns how his choices actually reflect who he aspires to be and how they lead to dire consequences.", publishedDate: "2010", author: "Amish Tripathi")
        let book18 = Book(image: "image18", name: "The Secret of the Nagas", description: "The Secret of the Nagas is the second book of Amish Tripathi, second book of Amishverse, and also the second book of Shiva Trilogy. The story takes place in the imaginary land of Meluha and narrates how the inhabitants of that land are saved from their wars by a nomad named Shiva. It begins from where its predecessor, The Immortals of Meluha, left off, with Shiva trying to save Sati from the invading Naga. Later Shiva takes his troop of soldiers and travels far east to the land of Branga, where he wishes to find a clue to reach the Naga people. Shiva also learns that Sati's first child is still alive, as well as her twin sister. His journey ultimately leads him to the Naga capital of Panchavati, where he finds a surprise waiting for him.", publishedDate: "2011", author: "Amish Tripathi")
        let book19 = Book(image: "image19", name: "The Oath of the Vayuputras", description: "The Oath of the Vayuputras is the third book of Amish Tripathi, third book of Amishverse, and also the third book of Shiva Trilogy.. The book was released on 27 February 2013, through Westland Press and completes the mythical story about an imaginary land Meluha and how its inhabitants were saved by a nomad named Shiva. Starting from where the previous installment left off, Shiva discovers what is the true evil in The Oath of the Vayuputras. Shiva then declares a holy war on those who seek to continue to use it, mainly the Emperors Daksha and Dilipa, who are being controlled by the sage Bhrigu. The battle rages on and Shiva travels to the land of Pariha to consult with Vayuputras, a legendary tribe. By the time he returns, the war has ended with Sati, his wife, being murdered. An enraged Shiva destroys the capital of Meluha and Somras is wiped out of history. The story concludes with Shiva and his associates being popularized as Gods for their deeds and accomplishments.", publishedDate: "2013", author: "Amish Tripath")
        let book20 = Book(image: "image20", name: "One Hundred Years of Solitude", description: "One Hundred Years of Solitude (Spanish: Cien años de soledad, American Spanish: [sjen ˈaɲos ðe soleˈðað]) is a landmark 1967 novel by Colombian author Gabriel García Márquez that tells the multi-generational story of the Buendía family, whose patriarch, José Arcadio Buendía, founded the (fictitious) town of Macondo, Colombia. The novel is often cited as one of the supreme achievements in literature.", publishedDate: "1970", author: "Gabriel García Márquez")
        booklist = [book1,book2,book3,book4,book5,book6,book7,book8,book9,book10,book11,book12,book13,book14,book15,book16,book17,book18,book19,book20]
        
    }
    
    
    func objectAt(_ indexpath: IndexPath) -> Book{
        return booklist[indexpath.row]
    }
    
    
    
    
}
